# Mark Shust's Magento Docker Compose (https://github.com/markoshust/magento-docker)
# Version 11.1.5

version: "3"

services:
  app:
    volumes: &appvolumes
      - magento2_appdata:/var/www/html:nocopy
      - ~/.composer:/var/www/html/var/composer_home

  phpfpm:
    volumes: *appvolumes

  db:
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
  magento2_appdata:
    external: true
