# Mage Inferno Docker Compose (https://github.com/mageinferno/magento2-docker-compose)
# Version 2.0.0

app:
  image: mageinferno/magento2-nginx:1.9.9-1
  ports:
    - "80:80"
  links:
    - php-fpm
    - db
  volumes_from:
    - appdata
  environment:
    - APP_MAGE_MODE=production
    - VIRTUAL_HOST=mysite.com

appdata:
  image: tianon/true
  volumes:
    - ./src:/src
    - ~/.composer:/root/.composer

"php-fpm":
  image: mageinferno/magento2-php:7.0.1-fpm-2
  links:
    - db
  volumes_from:
    - appdata
  environment:
    - APP_MAGE_MODE=production
    - PHP_MEMORY_LIMIT=4G

db:
  image: mariadb:10.0.23
  ports:
    - "3306:3306"
  volumes_from:
    - dbdata
  environment:
    - MYSQL_ROOT_PASSWORD=magento2
    - MYSQL_DATABASE=magento2
    - MYSQL_USER=magento2
    - MYSQL_PASSWORD=magento2

dbdata:
  image: tianon/true
  volumes:
    - /var/lib/mysql

setup:
  image: mageinferno/magento2-php:7.0.1-fpm-2
  command: /usr/local/bin/mage-setup
  links:
    - db
  volumes_from:
    - appdata
  environment:
    - M2SETUP_DB_HOST=db
    - M2SETUP_DB_NAME=magento2
    - M2SETUP_DB_USER=magento2
    - M2SETUP_DB_PASSWORD=magento2
    - M2SETUP_BASE_URL=http://mysite.com/
    - M2SETUP_ADMIN_FIRSTNAME=Admin
    - M2SETUP_ADMIN_LASTNAME=User
    - M2SETUP_ADMIN_EMAIL=dummy@gmail.com
    - M2SETUP_ADMIN_USER=magento2
    - M2SETUP_ADMIN_PASSWORD=magento2
    - M2SETUP_VERSION=2.0.0
    - M2SETUP_USE_SAMPLE_DATA=true
