# Mark Shust's Docker Configuration for Magento (https://github.com/markoshust/docker-magento)
# Version 12.0.0

version: "3"

services:
  app:
    image: markoshust/magento-nginx:1.13
    ports:
      - 80:8000
    links:
      - db
      - phpfpm
    volumes: &appvolumes
      - appdata:/var/www/html
      - ./src/app/code:/var/www/html/app/code:delegated
      - ./src/app/design:/var/www/html/app/design:delegated
      - ./src/app/i18n:/var/www/html/app/i18n:delegated
      - ~/.composer:/var/www/html/var/composer_home:delegated
      - sockdata:/sock

  phpfpm:
    image: markoshust/magento-php:7.1-fpm
    links:
      - db
    volumes: *appvolumes

  cron:
    image: markoshust/magento-php:7.1-fpm
    user: root
    command: /usr/local/bin/cronstart
    tty: true
    links:
      - db
    volumes: *appvolumes

  db:
    image: percona:5.7
    ports:
      - 3306:3306
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
  sockdata:
  appdata:
