## Mark Shust's Docker Configuration for Magento
## (https://github.com/markshust/docker-magento)
##
## Version 40.0.1

version: "3"

services:
  app:
    volumes: &appvolumes
      - ./src/nginx.conf.sample:/var/www/html/nginx.conf:cached

  ssh:
    image: markoshust/ssh
    ports:
      - "22:22"
    volumes: *appvolumes
